FORMAT: 1A
HOST: https://localhost:5000/

# Perfectly Balanced: a budgeting tool

This is the bestest API you have ever seen full stop.

#Group Transaction

## Transaction Collection [api/transactions]

### List all transaction [GET]

+ Relation: transactions
+ Request

    + Headers
    
            Accept: application/vnd.mason+json

+ Response 200 (application/vnd.mason+json)
    
    + Body

            {
                "@namespaces": {
                    "bumeta": {
                        "name": "/budgetmeta/link-relations#"
                    }
                },
                "@controls": {
                    "self": {
                        "href": "/api/transactions/"
                    },
                    "bumeta:add-transaction": {
                        "href": "/api/transactions/",
                        "title": "All transactions",
                        "encoding": "json",
                        "method": "POST",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "price": {
                                    "description": "Transaction amount",
                                    "type": "float"
                                },
                                "datetime": {
                                    "description": "Transaction date",
                                    "type": "string",
                                    "pattern": "^[0-9]{4}-[01][0-9]-[0-3][0-9]$"
                                },
                                "sender": {
                                    "description": "Who sent moneh",
                                    "type": "user object",
                                    "properties":{
                                        "username":{
                                            "description":"User's unique username",
                                            "type":"string"
                                        }
                                    }
                                },
                                "receiver": {
                                    "description": "Who got moneh",
                                    "type": "user object",
                                    "properties":{
                                        "username":{
                                            "description":"User's unique username",
                                            "type":"string"
                                        }
                                    }
                                },
                                "category": {
                                    "description": "Transaction category",
                                    "type": "string"
                                    }
                                },
                            "required": ["price", "sender", "receiver"]
                            }
                        }
                    },
                "items": [
                    {
                        "price": 10.0,
                        "datetime": "2021-02-20",
                        "sender": "Kalle Kallis",
                        "receiver": "Make Massinen",
                        "category": ["Food"],
                        "@controls": {
                            "self": {
                                "href": "/api/transactions/1/"
                            }
                        }
                    }
                ]
            }

### Add transaction to transactions [POST]

Adds a new album for the artist. The album representation must be valid against the album schema.

+ Relation: add-transaction
+ Request (application/json)

    + Headers

            Accept: application/vnd.mason+json
        
    + Body
    
            {
                "price": 100.0,
                "datetime": "2021-03-04",
                "sender": "Massi Päällikkö",
                "receiver": "Cash Money",
                "category": ["Utensils", "Kitchenware"]
            }

+ Response 201

    + Headers
    
            Location: /api/transactions/2/

<!-- TODO: add body -->
<!-- TODO: more responses? -->
+ Response 415


## Transaction [/api/transactions/{transaction}]

This resource represents a transaction, as identified by the transaction's id.
It includes the transactions metadata.
Transaction's sender and receiver can be referenced through it.

+ Parameters

    + transaction: 1 (integer) - transaction's id


### Transaction information [GET]

Get the transaction representation.

+ Relation: self
+ Request

    + Headers
    
            Accept: application/vnd.mason+json
        
+ Response 200 (application/vnd.mason+json)

    + Body
    
            {
                "@namespaces": {
                    "mumeta": {
                        "name": "/budgetmeta/link-relations#"
                    }
                },
                "price": 100.0,
                "datetime": "2021-03-04",
                "sender": "Massi Päällikkö",
                "receiver": "Cash Money",
                "category": ["Utensils", "Kitchenware"],
                "@controls": {
                    "self": {
                        "href": "/api/transactions/2/"
                    },
                    "bumeta:collection": {
                        "href": "/api/transactions/"
                    },
                    "bumeta:sender": {
                        "href": "/api/users/1/"
                    },
                    "bumeta:receiver": {
                        "href": "/api/users/2/"
                    },
                    "bumeta:delete": {
                        "href": "/api/transactions/2/",
                        "title": "Delete this transaction",
                        "method": "DELETE"
                    }
                }
            }

+ Response 404 (application/vnd.mason+json)

    The client is trying to access an transaction that does not exist.

    + Body

<!-- TODO: add body -->



## Category Collection [api/categories/]

### List all categories [GET]

+ Relation: categories
+ Request

    + Headers
    
            Accept: application/vnd.mason+json

+ Response 200 (application/vnd.mason+json)
    
    + Body

            {
                "@namespaces": {
                    "bumeta": {
                        "name": "/budgetmeta/link-relations#"
                    }
                },
                "@controls": {
                    "self": {
                        "href": "/api/categories/"
                    },
                    "bumeta:add-category": {
                        "href": "/api/categories/",
                        "title": "All categories",
                        "encoding": "json",
                        "method": "POST",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "categoryName": {
                                    "description": "Category name",
                                    "type": "string"
                                }
                            },
                            "required": ["categoryName"]
                            }
                        }
                    },
                "items": [
                    {
                        "categoryName": "Food",
                        "@controls": {
                            "self": {
                                "href": "/api/categories/1/"
                            }
                        }
                    }
                ]
            }

### Add category to categories [POST]

Adds a new category to the categories.
The category representation must be valid against the category schema.

+ Relation: add-category
+ Request (application/json)

    + Headers

            Accept: application/vnd.mason+json
        
    + Body
    
            {
                "categoryName": "Clothes"
            }

+ Response 201

    + Headers
    
            Location: /api/categories/3/

<!-- TODO: add body -->
<!-- TODO: more responses? -->
+ Response 415

## Category [/api/categories/{categoryName}]

This resource represents a transaction, as identified by the transaction's id.
It includes the transactions metadata.
Transaction's sender and receiver can be referenced through it.

+ Parameters

    + categoryName: 1 (string) - categorie's unique name


### Category information [GET]

Get the category representation.

+ Relation: self
+ Request

    + Headers
    
            Accept: application/vnd.mason+json
        
+ Response 200 (application/vnd.mason+json)

    + Body
    
            {
                "@namespaces": {
                    "mumeta": {
                        "name": "/budgetmeta/link-relations#"
                    }
                },
                "categoryName": "Clothes",
                "@controls": {
                    "self": {
                        "href": "/api/categories/Clothes/"
                    },
                    "bumeta:collection": {
                        "href": "/api/categories/"
                    },
                    "bumeta:transactions": {
                        "href": "/api/categories/Clothes/transactions/"
                    },
                    "bumeta:edit": {
                        "href": "/api/categories/Clothes/",
                        "title": "Edit this category",
                        "method": "PUT"
                    },
                    "bumeta:delete": {
                        "href": "/api/categories/Clothes/",
                        "title": "Delete this category",
                        "method": "DELETE"
                    }
                }
            }
            
## Users Collection [api/users/]

teksti

### List all users [GET]

+ Relation: users
+ Request

    + Headers
    
            Accept: application/vnd.mason+json

+ Response 200 (application/vnd.mason+json)
    
    + Body

            {
                "@namespaces": {
                    "bumeta": {
                        "name": "/budgetmeta/link-relations#"
                    }
                },
                "@controls": {
                    "self": {
                        "href": "/api/users/"
                    },
                    "bumeta:add-user": {
                        "href": "/api/users/",
                        "title": "All users",
                        "encoding": "json",
                        "method": "POST",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "username": {
                                    "description": "User's unique username",
                                    "type": "string"
                                },
                                "password": {
                                    "description": "User's password",
                                    "type": "string"
                                },
                                "bankAccount":{
                                    "description": "User's bankAccount",
                                    "type": "object",
                                    "properties":{
                                    "iban": {
                                        "description": "International bank account number",
                                        "type": "string"
                                    },
                                    "bankName": {
                                        "description": "Bank's name",
                                        "type": "string"
                                    }
                                    }
                                }
                                },
                            "required": ["username", "password", "bankAccount"]
                            }
                        }
                    },
                "items": [
                    {
                        "username": "Kalle Kallis",
                        "password": "pa55w0rd",
                        "bankAccount": "FI0000000001",

                        "@controls": {
                            "self": {
                                "href": "/api/users/1/"
                            }
                        }
                    }
                ]
            }

## User [/api/users/{username}]

This resource represents a user, as identified by the user's unique username
It includes the user's metadata.

+ Parameters

    + username: 1 (string) - user's unique name


### User information [GET]

Get the user representation.

+ Relation: self
+ Request

    + Headers
    
            Accept: application/vnd.mason+json
        
+ Response 200 (application/vnd.mason+json)

    + Body
    
            {
                "@namespaces": {
                    "mumeta": {
                        "name": "/budgetmeta/link-relations#"
                    }
                },
                "username": "Kalle Kallis",
                "password": "pa55w0rd",
                "bankAccount": "FI0000000001",
                "@controls": {
                    "self": {
                        "href": "/api/users/Kalle Kallis/"
                    },
                    "bumeta:collection": {
                        "href": "/api/users/"
                    },
                    "bumeta:transactions": {
                        "href": "/api/users/Kalle Kallis/transactions"
                    },
                    "bumeta:bank-account": {
                        "href": "/api/bankaccounts/1/"
                    },
                    "bumeta:edit": {
                        "href": "/api/users/Kalle Kallis/",
                        "title": "Edit this user",
                        "method": "PUT"
                    },
                    "bumeta:delete": {
                        "href": "/api/users/Kalle Kallis/",
                        "title": "Delete this user",
                        "method": "DELETE"
                    }
                }
            }

## Bank Account Collection [api/bankaccounts/]

### List all bank accounts [GET]

+ Relation: categories
+ Request

    + Headers
    
            Accept: application/vnd.mason+json

+ Response 200 (application/vnd.mason+json)
    
    + Body

            {
                "@namespaces": {
                    "bumeta": {
                        "name": "/budgetmeta/link-relations#"
                    }
                },
                "@controls": {
                    "self": {
                        "href": "/api/categories/"
                    },
                    "bumeta:add-category": {
                        "href": "/api/categories/",
                        "title": "All categories",
                        "encoding": "json",
                        "method": "POST",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "categoryName": {
                                    "description": "Category name",
                                    "type": "string"
                                }
                            },
                            "required": ["categoryName"]
                            }
                        }
                    },
                "items": [
                    {
                        "categoryName": "Food",
                        "@controls": {
                            "self": {
                                "href": "/api/categories/1/"
                            }
                        }
                    }
                ]
            }